release:
	tar --exclude='./.git' --exclude='./.gitignore' --exclude='./build_git.sh' --exclude='./LICENSE' --exclude='./Makefile' --exclude='./requirements.txt' --exclude='./*.md*' --exclude='./*.service*' --exclude='./*.tar.gz*' -czf rns_server_management.tar.gz .
